theme: jekyll-theme-cayman
title: Laundry Santuy
description: Laundry Santuy adalah sebuah aplikasi laundry yang dibuat untuk memudahkan pelanggan dalam melakukan pemesanan layanan laundry secara online. Dengan Laundry Santuy, pelanggan dapat dengan mudah memilih jenis layanan laundry yang diinginkan, menentukan jadwal pengambilan dan pengantaran, serta melakukan pembayaran secara online.
show_downloads: false
